{% set version = "1.9.1" %}

package:
  name: requests-mock
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/requests-mock/requests-mock-{{ version }}.tar.gz
  sha256: 154903e7646b8215fbdccc6898c32a77b87d2fbafad2f43e99d6d7987dc86953

build:
  number: 0
  script: python -m pip install . --no-deps --ignore-installed
  noarch: python

requirements:
  host:
    - pbr
    - pip
    - python 2.7|>=3.4
  run:
    - python 2.7|>=3.4
    - requests >=2.3
    - six

test:
  imports:
    - requests_mock

about:
  home: https://github.com/jamielennox/requests-mock
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: requests-mock provides a building block to stub out the HTTP requests portions of your testing code.
  description: requests-mock provides a building block to stub out the HTTP requests portions of your testing code.
  doc_url: https://requests-mock.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - nicoddemus
