{% set version = "1.7.0" %}

package:
  name: requests-mock
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/requests-mock/requests-mock-{{ version }}.tar.gz
  sha256: 88d3402dd8b3c69a9e4f9d3a73ad11b15920c6efd36bc27bf1f701cf4a8e4646

build:
  number: 0
  script: python -m pip install . --no-deps --ignore-installed
  noarch: python

requirements:
  build:
    - pbr
    - pip
    - python
  run:
    - python
    - requests >=2.3
    - six

test:
  imports:
    - requests_mock

about:
  home: https://github.com/jamielennox/requests-mock
  license: Apache 2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "requests-mock provides a building block to stub out the HTTP requests portions of your testing code."
  description: "requests-mock provides a building block to stub out the HTTP requests portions of your testing code."
  doc_url: https://requests-mock.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - nicoddemus
