{% set name = "requests-mock" %}
{% set version = "1.12.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e9e12e333b525156e82a3c852f22016b9158220d2f47454de9cae8a77d371401

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{version}}

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
    - wheel
  run:
    - python
    - requests >=2.22,<3

test:
  imports:
    - requests_mock
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jamielennox/requests-mock
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: requests-mock provides a building block to stub out the HTTP requests portions of your testing code.
  description: requests-mock provides a building block to stub out the HTTP requests portions of your testing code.
  doc_url: https://requests-mock.readthedocs.io
  dev_url: https://github.com/jamielennox/requests-mock

extra:
  recipe-maintainers:
    - nicoddemus
