travis:
  secure:
    BINSTAR_TOKEN: hT6Agp8y7FYec1a88PjOIPpTlMHYQDRJY1jZ1GeN+1nV79qFJKAEBI3bmh1V4/NpR3FCsNQwGJquPTOP0w3s+pKGvbjzftDdpqTC/X32t3L3li+LAuBe3j2JRe0dYim27ZVZ2gkDil7MOwt57lsg4w8H0mixyiihfpVtB0J2KGHIQR2qfrYRBzZwa3zVCSP/IFR/K6Ysmm2RwR9o9G2f4xJzuiEeWdgzTeInRje5s6LBxhm375lk3Yq73mN3o6a27omhV18MT/yqa3BV/ocdhDAiHqqZbNoUYCshuSSzuDriau445WMZnC8fIuJaKAl5N+AxwwyDvwV0gDUrq5zGzRhXqC8HtwZy4JCcHeQ3kCBVndDUHdfLXTTh1mKgXfQOzxsq8U51QuJxaEWQWQIKq64w5CcIFq9qK3rzsx3ftCCCVUNDfxdraAZaedsGV427JnigJuTgmzj3uqJcSlMgbF0XafqJWxA2O8ofUn9/GPpkoAxvNlc4ulMwZoo3V3tKdkxnZbnR9diRujtorah1LI7DjCV7fqX7TEi3ZAEUkchecXgTVt14BqATHqHqG+j2TTkot4Ckkn3zyG46G7j+LY3uhQ0l4hyEDIPeBXBRsda6XGQWSuzZal28k1AJCCV/Ooe2V7R9iekZfu4Ln3cAIn8nE2Du1H80yTFjqSC1Q8M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
