travis:
  secure:
    BINSTAR_TOKEN: juF4gIVG9gVfYkZOpk4G5DgXKuvvAPD68PEx/A5CNP6R2ybKV2p82ReLDnWvb+QMlI3euqKH+hRVT81uY8hG++XYH4N5W9FhYk42DLhtjFk2L2HwPS0l8nx7nFJMPq7EnYkOcQb9fDLV936PxMK7uwBafYZX8RCN76R/oPMgDW0mzvdUX/anaJRAmiVR9jovfxF+xr1bQsK9k+RrsVlWHNr2L5heyuHJ/lsTVkz8a22QytPK6fg0Q95nYIJJvKGgARTr4AqogwGWSP0jSavWUp6m+HPdZGBGzwBC3ZvFKzflUxLKqA4G5Fkx5V4GFYPFEwapslXX77Mfiy7Vzlg5ozii5vl1AqFuZxsarsjrkDB+xU6eP6WsiZmG5c9Edkgt5hIi3zK74fs4RTq/lkdn9sxbXi/yXqkNZTdf9V06q8fby8GgF4jvDbVVKzjerXo6fBW7wrWiGrsDipS1pF2N9wNHJIWqfN2V9cvpEit1YQMg1QXHpyy1ev4v68PhwsUliwSIYnlUep+UP98TCL4obQ9wjuZSViiiAQmeLBi45Uj7wO9p2F3+LeUvVnXLJnorLvmV7KTJzBNGmOAgQmdATJ/beW7i0YyYwZSw8oMtXkp5RkT3NDdv/NhkUfbAHYrOQdyKqCVpoXSKarPNCFkFBFvkI8dIL8RZtlxole+jzYI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
